/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "SBI.iot.common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SBI_iot_common_FanspeedSet, SBI_iot_common_FanspeedSet, AUTO)


PB_BIND(SBI_iot_common_TemperatureSetPoint, SBI_iot_common_TemperatureSetPoint, AUTO)


PB_BIND(SBI_iot_common_Date, SBI_iot_common_Date, AUTO)


PB_BIND(SBI_iot_common_Time, SBI_iot_common_Time, AUTO)


PB_BIND(SBI_iot_common_DateTime, SBI_iot_common_DateTime, AUTO)


PB_BIND(SBI_iot_common_Version, SBI_iot_common_Version, AUTO)





