/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_SBI_IOT_SBI_IOT_PB_H_INCLUDED
#define PB_SBI_IOT_SBI_IOT_PB_H_INCLUDED
#include <pb.h>
#include "SBI.iot.common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SBI_iot_EQOS { 
    SBI_iot_EQOS_EQOS_FireAndForget = 0, 
    SBI_iot_EQOS_EQOS_NeedAcknowledge = 1 
} SBI_iot_EQOS;

typedef enum _SBI_iot_EDEVICETYPE { 
    SBI_iot_EDEVICETYPE_EDEVICETYPE_None = 0, 
    SBI_iot_EDEVICETYPE_EDEVICETYPE_IoTServer_V1 = 1, 
    SBI_iot_EDEVICETYPE_EDEVICETYPE_Remote_V1 = 2 
} SBI_iot_EDEVICETYPE;

typedef enum _SBI_iot_ESTOVESTATE { 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_ZEROING_STEPPER = 0, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_WAITING = 1, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_RELOAD_IGNITION = 2, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_TEMPERATURE_RISE = 3, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_HIGH = 4, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_LOW = 5, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_SUPERLOW = 6, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COAL_LOW = 7, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_FLAME_LOSS = 8, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COAL_HIGH = 9, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_OVERTEMP = 10, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_SAFETY = 11, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_PRODUCTION_TEST = 12, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_HIGH_OPEN = 13, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_HIGH_CLOSE = 14, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_LOW_OPEN = 15, 
    SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_LOW_CLOSE = 16 
} SBI_iot_ESTOVESTATE;

typedef enum _SBI_iot_C2SPairingReqResp_EResponse { 
    SBI_iot_C2SPairingReqResp_EResponse_OK = 0, 
    SBI_iot_C2SPairingReqResp_EResponse_IncompatibleDevice = 1, 
    SBI_iot_C2SPairingReqResp_EResponse_InvalidKey = 2 
} SBI_iot_C2SPairingReqResp_EResponse;

/* Struct definitions */
typedef struct _SBI_iot_C2SChangeSettingSP { 
    /* New settings, the stove can refuse new settings */
    bool has_fan_speed_set;
    SBI_iot_common_FanspeedSet fan_speed_set;
    bool has_temperature_set;
    SBI_iot_common_TemperatureSet temperature_set;
} SBI_iot_C2SChangeSettingSP;

typedef struct _SBI_iot_DeviceInfo { 
    SBI_iot_EDEVICETYPE device_type;
    bool has_sw_version;
    SBI_iot_common_Version sw_version;
} SBI_iot_DeviceInfo;

typedef struct _SBI_iot_RemoteState { 
    float temperatureC_curr;
    float humidityPerc_curr;
} SBI_iot_RemoteState;

typedef struct _SBI_iot_S2CChangeSettingSPResp { 
    bool has_fan_speed_set;
    SBI_iot_common_FanspeedSet fan_speed_set;
    bool has_temperature_set;
    SBI_iot_common_TemperatureSet temperature_set;
} SBI_iot_S2CChangeSettingSPResp;

typedef struct _SBI_iot_S2CGetStatusResp_StoveState { 
    bool has_fan_speed_set;
    SBI_iot_common_FanspeedSet fan_speed_set;
    bool has_temperature_set;
    SBI_iot_common_TemperatureSet temperature_set;
    bool has_datetime;
    SBI_iot_common_DateTime datetime;
} SBI_iot_S2CGetStatusResp_StoveState;

typedef struct _SBI_iot_C2SGetStatus { 
    bool has_remote_state;
    SBI_iot_RemoteState remote_state;
} SBI_iot_C2SGetStatus;

typedef struct _SBI_iot_C2SPairingReq { 
    bool has_device_info;
    SBI_iot_DeviceInfo device_info;
    pb_callback_t encryption_key;
} SBI_iot_C2SPairingReq;

typedef struct _SBI_iot_C2SPairingReqResp { 
    bool has_device_info;
    SBI_iot_DeviceInfo device_info;
    SBI_iot_C2SPairingReqResp_EResponse response;
} SBI_iot_C2SPairingReqResp;

typedef struct _SBI_iot_C2SScan { 
    bool has_device_info;
    SBI_iot_DeviceInfo device_info;
} SBI_iot_C2SScan;

typedef struct _SBI_iot_S2CGetStatusResp { 
    bool has_device_info;
    SBI_iot_DeviceInfo device_info;
    bool has_stove_state;
    SBI_iot_S2CGetStatusResp_StoveState stove_state;
} SBI_iot_S2CGetStatusResp;

typedef struct _SBI_iot_S2CScanResp { 
    bool has_device_info;
    SBI_iot_DeviceInfo device_info;
} SBI_iot_S2CScanResp;

typedef struct _SBI_iot_Cmd { 
    uint32_t seq_number;
    SBI_iot_EQOS eQoS;
    pb_size_t which_payload;
    union {
        SBI_iot_C2SScan c2s_scan;
        SBI_iot_S2CScanResp s2c_scan_resp;
        SBI_iot_C2SGetStatus c2s_get_status;
        SBI_iot_S2CGetStatusResp s2c_get_status_resp;
        SBI_iot_C2SChangeSettingSP c2s_change_settingsp;
        SBI_iot_S2CChangeSettingSPResp s2c_change_settingsp_resp;
    } payload;
} SBI_iot_Cmd;


/* Helper constants for enums */
#define _SBI_iot_EQOS_MIN SBI_iot_EQOS_EQOS_FireAndForget
#define _SBI_iot_EQOS_MAX SBI_iot_EQOS_EQOS_NeedAcknowledge
#define _SBI_iot_EQOS_ARRAYSIZE ((SBI_iot_EQOS)(SBI_iot_EQOS_EQOS_NeedAcknowledge+1))

#define _SBI_iot_EDEVICETYPE_MIN SBI_iot_EDEVICETYPE_EDEVICETYPE_None
#define _SBI_iot_EDEVICETYPE_MAX SBI_iot_EDEVICETYPE_EDEVICETYPE_Remote_V1
#define _SBI_iot_EDEVICETYPE_ARRAYSIZE ((SBI_iot_EDEVICETYPE)(SBI_iot_EDEVICETYPE_EDEVICETYPE_Remote_V1+1))

#define _SBI_iot_ESTOVESTATE_MIN SBI_iot_ESTOVESTATE_ESTOVESTATE_ZEROING_STEPPER
#define _SBI_iot_ESTOVESTATE_MAX SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_LOW_CLOSE
#define _SBI_iot_ESTOVESTATE_ARRAYSIZE ((SBI_iot_ESTOVESTATE)(SBI_iot_ESTOVESTATE_ESTOVESTATE_COMBUSTION_LOW_CLOSE+1))

#define _SBI_iot_C2SPairingReqResp_EResponse_MIN SBI_iot_C2SPairingReqResp_EResponse_OK
#define _SBI_iot_C2SPairingReqResp_EResponse_MAX SBI_iot_C2SPairingReqResp_EResponse_InvalidKey
#define _SBI_iot_C2SPairingReqResp_EResponse_ARRAYSIZE ((SBI_iot_C2SPairingReqResp_EResponse)(SBI_iot_C2SPairingReqResp_EResponse_InvalidKey+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SBI_iot_DeviceInfo_init_default          {_SBI_iot_EDEVICETYPE_MIN, false, SBI_iot_common_Version_init_default}
#define SBI_iot_RemoteState_init_default         {0, 0}
#define SBI_iot_C2SGetStatus_init_default        {false, SBI_iot_RemoteState_init_default}
#define SBI_iot_S2CGetStatusResp_init_default    {false, SBI_iot_DeviceInfo_init_default, false, SBI_iot_S2CGetStatusResp_StoveState_init_default}
#define SBI_iot_S2CGetStatusResp_StoveState_init_default {false, SBI_iot_common_FanspeedSet_init_default, false, SBI_iot_common_TemperatureSet_init_default, false, SBI_iot_common_DateTime_init_default}
#define SBI_iot_C2SChangeSettingSP_init_default  {false, SBI_iot_common_FanspeedSet_init_default, false, SBI_iot_common_TemperatureSet_init_default}
#define SBI_iot_S2CChangeSettingSPResp_init_default {false, SBI_iot_common_FanspeedSet_init_default, false, SBI_iot_common_TemperatureSet_init_default}
#define SBI_iot_C2SScan_init_default             {false, SBI_iot_DeviceInfo_init_default}
#define SBI_iot_S2CScanResp_init_default         {false, SBI_iot_DeviceInfo_init_default}
#define SBI_iot_C2SPairingReq_init_default       {false, SBI_iot_DeviceInfo_init_default, {{NULL}, NULL}}
#define SBI_iot_C2SPairingReqResp_init_default   {false, SBI_iot_DeviceInfo_init_default, _SBI_iot_C2SPairingReqResp_EResponse_MIN}
#define SBI_iot_Cmd_init_default                 {0, _SBI_iot_EQOS_MIN, 0, {SBI_iot_C2SScan_init_default}}
#define SBI_iot_DeviceInfo_init_zero             {_SBI_iot_EDEVICETYPE_MIN, false, SBI_iot_common_Version_init_zero}
#define SBI_iot_RemoteState_init_zero            {0, 0}
#define SBI_iot_C2SGetStatus_init_zero           {false, SBI_iot_RemoteState_init_zero}
#define SBI_iot_S2CGetStatusResp_init_zero       {false, SBI_iot_DeviceInfo_init_zero, false, SBI_iot_S2CGetStatusResp_StoveState_init_zero}
#define SBI_iot_S2CGetStatusResp_StoveState_init_zero {false, SBI_iot_common_FanspeedSet_init_zero, false, SBI_iot_common_TemperatureSet_init_zero, false, SBI_iot_common_DateTime_init_zero}
#define SBI_iot_C2SChangeSettingSP_init_zero     {false, SBI_iot_common_FanspeedSet_init_zero, false, SBI_iot_common_TemperatureSet_init_zero}
#define SBI_iot_S2CChangeSettingSPResp_init_zero {false, SBI_iot_common_FanspeedSet_init_zero, false, SBI_iot_common_TemperatureSet_init_zero}
#define SBI_iot_C2SScan_init_zero                {false, SBI_iot_DeviceInfo_init_zero}
#define SBI_iot_S2CScanResp_init_zero            {false, SBI_iot_DeviceInfo_init_zero}
#define SBI_iot_C2SPairingReq_init_zero          {false, SBI_iot_DeviceInfo_init_zero, {{NULL}, NULL}}
#define SBI_iot_C2SPairingReqResp_init_zero      {false, SBI_iot_DeviceInfo_init_zero, _SBI_iot_C2SPairingReqResp_EResponse_MIN}
#define SBI_iot_Cmd_init_zero                    {0, _SBI_iot_EQOS_MIN, 0, {SBI_iot_C2SScan_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SBI_iot_C2SChangeSettingSP_fan_speed_set_tag 1
#define SBI_iot_C2SChangeSettingSP_temperature_set_tag 2
#define SBI_iot_DeviceInfo_device_type_tag       1
#define SBI_iot_DeviceInfo_sw_version_tag        2
#define SBI_iot_RemoteState_temperatureC_curr_tag 1
#define SBI_iot_RemoteState_humidityPerc_curr_tag 2
#define SBI_iot_S2CChangeSettingSPResp_fan_speed_set_tag 1
#define SBI_iot_S2CChangeSettingSPResp_temperature_set_tag 2
#define SBI_iot_S2CGetStatusResp_StoveState_fan_speed_set_tag 1
#define SBI_iot_S2CGetStatusResp_StoveState_temperature_set_tag 2
#define SBI_iot_S2CGetStatusResp_StoveState_datetime_tag 6
#define SBI_iot_C2SGetStatus_remote_state_tag    1
#define SBI_iot_C2SPairingReq_device_info_tag    1
#define SBI_iot_C2SPairingReq_encryption_key_tag 2
#define SBI_iot_C2SPairingReqResp_device_info_tag 1
#define SBI_iot_C2SPairingReqResp_response_tag   2
#define SBI_iot_C2SScan_device_info_tag          1
#define SBI_iot_S2CGetStatusResp_device_info_tag 1
#define SBI_iot_S2CGetStatusResp_stove_state_tag 2
#define SBI_iot_S2CScanResp_device_info_tag      1
#define SBI_iot_Cmd_seq_number_tag               1
#define SBI_iot_Cmd_eQoS_tag                     2
#define SBI_iot_Cmd_c2s_scan_tag                 32
#define SBI_iot_Cmd_s2c_scan_resp_tag            33
#define SBI_iot_Cmd_c2s_get_status_tag           34
#define SBI_iot_Cmd_s2c_get_status_resp_tag      35
#define SBI_iot_Cmd_c2s_change_settingsp_tag     36
#define SBI_iot_Cmd_s2c_change_settingsp_resp_tag 37

/* Struct field encoding specification for nanopb */
#define SBI_iot_DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sw_version,        2)
#define SBI_iot_DeviceInfo_CALLBACK NULL
#define SBI_iot_DeviceInfo_DEFAULT NULL
#define SBI_iot_DeviceInfo_sw_version_MSGTYPE SBI_iot_common_Version

#define SBI_iot_RemoteState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperatureC_curr,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidityPerc_curr,   2)
#define SBI_iot_RemoteState_CALLBACK NULL
#define SBI_iot_RemoteState_DEFAULT NULL

#define SBI_iot_C2SGetStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  remote_state,      1)
#define SBI_iot_C2SGetStatus_CALLBACK NULL
#define SBI_iot_C2SGetStatus_DEFAULT NULL
#define SBI_iot_C2SGetStatus_remote_state_MSGTYPE SBI_iot_RemoteState

#define SBI_iot_S2CGetStatusResp_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stove_state,       2)
#define SBI_iot_S2CGetStatusResp_CALLBACK NULL
#define SBI_iot_S2CGetStatusResp_DEFAULT NULL
#define SBI_iot_S2CGetStatusResp_device_info_MSGTYPE SBI_iot_DeviceInfo
#define SBI_iot_S2CGetStatusResp_stove_state_MSGTYPE SBI_iot_S2CGetStatusResp_StoveState

#define SBI_iot_S2CGetStatusResp_StoveState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fan_speed_set,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  temperature_set,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  datetime,          6)
#define SBI_iot_S2CGetStatusResp_StoveState_CALLBACK NULL
#define SBI_iot_S2CGetStatusResp_StoveState_DEFAULT NULL
#define SBI_iot_S2CGetStatusResp_StoveState_fan_speed_set_MSGTYPE SBI_iot_common_FanspeedSet
#define SBI_iot_S2CGetStatusResp_StoveState_temperature_set_MSGTYPE SBI_iot_common_TemperatureSet
#define SBI_iot_S2CGetStatusResp_StoveState_datetime_MSGTYPE SBI_iot_common_DateTime

#define SBI_iot_C2SChangeSettingSP_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fan_speed_set,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  temperature_set,   2)
#define SBI_iot_C2SChangeSettingSP_CALLBACK NULL
#define SBI_iot_C2SChangeSettingSP_DEFAULT NULL
#define SBI_iot_C2SChangeSettingSP_fan_speed_set_MSGTYPE SBI_iot_common_FanspeedSet
#define SBI_iot_C2SChangeSettingSP_temperature_set_MSGTYPE SBI_iot_common_TemperatureSet

#define SBI_iot_S2CChangeSettingSPResp_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fan_speed_set,     1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  temperature_set,   2)
#define SBI_iot_S2CChangeSettingSPResp_CALLBACK NULL
#define SBI_iot_S2CChangeSettingSPResp_DEFAULT NULL
#define SBI_iot_S2CChangeSettingSPResp_fan_speed_set_MSGTYPE SBI_iot_common_FanspeedSet
#define SBI_iot_S2CChangeSettingSPResp_temperature_set_MSGTYPE SBI_iot_common_TemperatureSet

#define SBI_iot_C2SScan_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1)
#define SBI_iot_C2SScan_CALLBACK NULL
#define SBI_iot_C2SScan_DEFAULT NULL
#define SBI_iot_C2SScan_device_info_MSGTYPE SBI_iot_DeviceInfo

#define SBI_iot_S2CScanResp_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1)
#define SBI_iot_S2CScanResp_CALLBACK NULL
#define SBI_iot_S2CScanResp_DEFAULT NULL
#define SBI_iot_S2CScanResp_device_info_MSGTYPE SBI_iot_DeviceInfo

#define SBI_iot_C2SPairingReq_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1) \
X(a, CALLBACK, SINGULAR, BYTES,    encryption_key,    2)
#define SBI_iot_C2SPairingReq_CALLBACK pb_default_field_callback
#define SBI_iot_C2SPairingReq_DEFAULT NULL
#define SBI_iot_C2SPairingReq_device_info_MSGTYPE SBI_iot_DeviceInfo

#define SBI_iot_C2SPairingReqResp_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1) \
X(a, STATIC,   SINGULAR, UENUM,    response,          2)
#define SBI_iot_C2SPairingReqResp_CALLBACK NULL
#define SBI_iot_C2SPairingReqResp_DEFAULT NULL
#define SBI_iot_C2SPairingReqResp_device_info_MSGTYPE SBI_iot_DeviceInfo

#define SBI_iot_Cmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq_number,        1) \
X(a, STATIC,   SINGULAR, UENUM,    eQoS,              2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,c2s_scan,payload.c2s_scan),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,s2c_scan_resp,payload.s2c_scan_resp),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,c2s_get_status,payload.c2s_get_status),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,s2c_get_status_resp,payload.s2c_get_status_resp),  35) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,c2s_change_settingsp,payload.c2s_change_settingsp),  36) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,s2c_change_settingsp_resp,payload.s2c_change_settingsp_resp),  37)
#define SBI_iot_Cmd_CALLBACK NULL
#define SBI_iot_Cmd_DEFAULT NULL
#define SBI_iot_Cmd_payload_c2s_scan_MSGTYPE SBI_iot_C2SScan
#define SBI_iot_Cmd_payload_s2c_scan_resp_MSGTYPE SBI_iot_S2CScanResp
#define SBI_iot_Cmd_payload_c2s_get_status_MSGTYPE SBI_iot_C2SGetStatus
#define SBI_iot_Cmd_payload_s2c_get_status_resp_MSGTYPE SBI_iot_S2CGetStatusResp
#define SBI_iot_Cmd_payload_c2s_change_settingsp_MSGTYPE SBI_iot_C2SChangeSettingSP
#define SBI_iot_Cmd_payload_s2c_change_settingsp_resp_MSGTYPE SBI_iot_S2CChangeSettingSPResp

extern const pb_msgdesc_t SBI_iot_DeviceInfo_msg;
extern const pb_msgdesc_t SBI_iot_RemoteState_msg;
extern const pb_msgdesc_t SBI_iot_C2SGetStatus_msg;
extern const pb_msgdesc_t SBI_iot_S2CGetStatusResp_msg;
extern const pb_msgdesc_t SBI_iot_S2CGetStatusResp_StoveState_msg;
extern const pb_msgdesc_t SBI_iot_C2SChangeSettingSP_msg;
extern const pb_msgdesc_t SBI_iot_S2CChangeSettingSPResp_msg;
extern const pb_msgdesc_t SBI_iot_C2SScan_msg;
extern const pb_msgdesc_t SBI_iot_S2CScanResp_msg;
extern const pb_msgdesc_t SBI_iot_C2SPairingReq_msg;
extern const pb_msgdesc_t SBI_iot_C2SPairingReqResp_msg;
extern const pb_msgdesc_t SBI_iot_Cmd_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SBI_iot_DeviceInfo_fields &SBI_iot_DeviceInfo_msg
#define SBI_iot_RemoteState_fields &SBI_iot_RemoteState_msg
#define SBI_iot_C2SGetStatus_fields &SBI_iot_C2SGetStatus_msg
#define SBI_iot_S2CGetStatusResp_fields &SBI_iot_S2CGetStatusResp_msg
#define SBI_iot_S2CGetStatusResp_StoveState_fields &SBI_iot_S2CGetStatusResp_StoveState_msg
#define SBI_iot_C2SChangeSettingSP_fields &SBI_iot_C2SChangeSettingSP_msg
#define SBI_iot_S2CChangeSettingSPResp_fields &SBI_iot_S2CChangeSettingSPResp_msg
#define SBI_iot_C2SScan_fields &SBI_iot_C2SScan_msg
#define SBI_iot_S2CScanResp_fields &SBI_iot_S2CScanResp_msg
#define SBI_iot_C2SPairingReq_fields &SBI_iot_C2SPairingReq_msg
#define SBI_iot_C2SPairingReqResp_fields &SBI_iot_C2SPairingReqResp_msg
#define SBI_iot_Cmd_fields &SBI_iot_Cmd_msg

/* Maximum encoded size of messages (where known) */
/* SBI_iot_C2SPairingReq_size depends on runtime parameters */
#define SBI_iot_C2SChangeSettingSP_size          17
#define SBI_iot_C2SGetStatus_size                12
#define SBI_iot_C2SPairingReqResp_size           26
#define SBI_iot_C2SScan_size                     24
#define SBI_iot_Cmd_size                         102
#define SBI_iot_DeviceInfo_size                  22
#define SBI_iot_RemoteState_size                 10
#define SBI_iot_S2CChangeSettingSPResp_size      17
#define SBI_iot_S2CGetStatusResp_StoveState_size 65
#define SBI_iot_S2CGetStatusResp_size            91
#define SBI_iot_S2CScanResp_size                 24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
