/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "SBI.iot.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SBI_iot_DeviceInfo, SBI_iot_DeviceInfo, AUTO)


PB_BIND(SBI_iot_RemoteState, SBI_iot_RemoteState, AUTO)


PB_BIND(SBI_iot_C2SGetStatus, SBI_iot_C2SGetStatus, AUTO)


PB_BIND(SBI_iot_S2CGetStatusResp, SBI_iot_S2CGetStatusResp, AUTO)


PB_BIND(SBI_iot_S2CGetStatusResp_StoveState, SBI_iot_S2CGetStatusResp_StoveState, AUTO)


PB_BIND(SBI_iot_C2SChangeSettingSP, SBI_iot_C2SChangeSettingSP, AUTO)


PB_BIND(SBI_iot_S2CChangeSettingSPResp, SBI_iot_S2CChangeSettingSPResp, AUTO)


PB_BIND(SBI_iot_C2SScan, SBI_iot_C2SScan, AUTO)


PB_BIND(SBI_iot_S2CScanResp, SBI_iot_S2CScanResp, AUTO)


PB_BIND(SBI_iot_C2SPairingReq, SBI_iot_C2SPairingReq, AUTO)


PB_BIND(SBI_iot_C2SPairingReqResp, SBI_iot_C2SPairingReqResp, AUTO)


PB_BIND(SBI_iot_Cmd, SBI_iot_Cmd, AUTO)







