/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_SBI_IOT_COMMON_SBI_IOT_COMMON_PB_H_INCLUDED
#define PB_SBI_IOT_COMMON_SBI_IOT_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SBI_iot_common_ETEMPERATUREUNIT { 
    SBI_iot_common_ETEMPERATUREUNIT_Celcius = 0, 
    SBI_iot_common_ETEMPERATUREUNIT_Farenheit = 1 
} SBI_iot_common_ETEMPERATUREUNIT;

/* Struct definitions */
typedef struct _SBI_iot_common_Date { 
    uint32_t year;
    uint32_t month;
    uint32_t day;
} SBI_iot_common_Date;

typedef struct _SBI_iot_common_FanspeedBoundary { 
    uint32_t min;
    uint32_t max;
} SBI_iot_common_FanspeedBoundary;

typedef struct _SBI_iot_common_FanspeedSet { 
    bool is_automatic;
    uint32_t curr;
} SBI_iot_common_FanspeedSet;

typedef struct _SBI_iot_common_TemperatureSetPoint { 
    SBI_iot_common_ETEMPERATUREUNIT unit;
    float temp;
} SBI_iot_common_TemperatureSetPoint;

typedef struct _SBI_iot_common_Time { 
    uint32_t hour;
    uint32_t min;
    uint32_t sec;
    uint32_t millis;
} SBI_iot_common_Time;

typedef struct _SBI_iot_common_Version { 
    uint32_t major;
    uint32_t minor;
    uint32_t revision;
} SBI_iot_common_Version;

typedef struct _SBI_iot_common_DateTime { 
    bool has_date;
    SBI_iot_common_Date date;
    bool has_time;
    SBI_iot_common_Time time;
} SBI_iot_common_DateTime;


/* Helper constants for enums */
#define _SBI_iot_common_ETEMPERATUREUNIT_MIN SBI_iot_common_ETEMPERATUREUNIT_Celcius
#define _SBI_iot_common_ETEMPERATUREUNIT_MAX SBI_iot_common_ETEMPERATUREUNIT_Farenheit
#define _SBI_iot_common_ETEMPERATUREUNIT_ARRAYSIZE ((SBI_iot_common_ETEMPERATUREUNIT)(SBI_iot_common_ETEMPERATUREUNIT_Farenheit+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SBI_iot_common_FanspeedSet_init_default  {0, 0}
#define SBI_iot_common_FanspeedBoundary_init_default {0, 0}
#define SBI_iot_common_TemperatureSetPoint_init_default {_SBI_iot_common_ETEMPERATUREUNIT_MIN, 0}
#define SBI_iot_common_Date_init_default         {0, 0, 0}
#define SBI_iot_common_Time_init_default         {0, 0, 0, 0}
#define SBI_iot_common_DateTime_init_default     {false, SBI_iot_common_Date_init_default, false, SBI_iot_common_Time_init_default}
#define SBI_iot_common_Version_init_default      {0, 0, 0}
#define SBI_iot_common_FanspeedSet_init_zero     {0, 0}
#define SBI_iot_common_FanspeedBoundary_init_zero {0, 0}
#define SBI_iot_common_TemperatureSetPoint_init_zero {_SBI_iot_common_ETEMPERATUREUNIT_MIN, 0}
#define SBI_iot_common_Date_init_zero            {0, 0, 0}
#define SBI_iot_common_Time_init_zero            {0, 0, 0, 0}
#define SBI_iot_common_DateTime_init_zero        {false, SBI_iot_common_Date_init_zero, false, SBI_iot_common_Time_init_zero}
#define SBI_iot_common_Version_init_zero         {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SBI_iot_common_Date_year_tag             1
#define SBI_iot_common_Date_month_tag            2
#define SBI_iot_common_Date_day_tag              3
#define SBI_iot_common_FanspeedBoundary_min_tag  1
#define SBI_iot_common_FanspeedBoundary_max_tag  2
#define SBI_iot_common_FanspeedSet_is_automatic_tag 1
#define SBI_iot_common_FanspeedSet_curr_tag      2
#define SBI_iot_common_TemperatureSetPoint_unit_tag 1
#define SBI_iot_common_TemperatureSetPoint_temp_tag 2
#define SBI_iot_common_Time_hour_tag             1
#define SBI_iot_common_Time_min_tag              2
#define SBI_iot_common_Time_sec_tag              3
#define SBI_iot_common_Time_millis_tag           4
#define SBI_iot_common_Version_major_tag         1
#define SBI_iot_common_Version_minor_tag         2
#define SBI_iot_common_Version_revision_tag      3
#define SBI_iot_common_DateTime_date_tag         1
#define SBI_iot_common_DateTime_time_tag         2

/* Struct field encoding specification for nanopb */
#define SBI_iot_common_FanspeedSet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_automatic,      1) \
X(a, STATIC,   SINGULAR, UINT32,   curr,              2)
#define SBI_iot_common_FanspeedSet_CALLBACK NULL
#define SBI_iot_common_FanspeedSet_DEFAULT NULL

#define SBI_iot_common_FanspeedBoundary_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   min,               1) \
X(a, STATIC,   SINGULAR, UINT32,   max,               2)
#define SBI_iot_common_FanspeedBoundary_CALLBACK NULL
#define SBI_iot_common_FanspeedBoundary_DEFAULT NULL

#define SBI_iot_common_TemperatureSetPoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    unit,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              2)
#define SBI_iot_common_TemperatureSetPoint_CALLBACK NULL
#define SBI_iot_common_TemperatureSetPoint_DEFAULT NULL

#define SBI_iot_common_Date_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   year,              1) \
X(a, STATIC,   SINGULAR, UINT32,   month,             2) \
X(a, STATIC,   SINGULAR, UINT32,   day,               3)
#define SBI_iot_common_Date_CALLBACK NULL
#define SBI_iot_common_Date_DEFAULT NULL

#define SBI_iot_common_Time_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   hour,              1) \
X(a, STATIC,   SINGULAR, UINT32,   min,               2) \
X(a, STATIC,   SINGULAR, UINT32,   sec,               3) \
X(a, STATIC,   SINGULAR, UINT32,   millis,            4)
#define SBI_iot_common_Time_CALLBACK NULL
#define SBI_iot_common_Time_DEFAULT NULL

#define SBI_iot_common_DateTime_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  date,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              2)
#define SBI_iot_common_DateTime_CALLBACK NULL
#define SBI_iot_common_DateTime_DEFAULT NULL
#define SBI_iot_common_DateTime_date_MSGTYPE SBI_iot_common_Date
#define SBI_iot_common_DateTime_time_MSGTYPE SBI_iot_common_Time

#define SBI_iot_common_Version_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2) \
X(a, STATIC,   SINGULAR, UINT32,   revision,          3)
#define SBI_iot_common_Version_CALLBACK NULL
#define SBI_iot_common_Version_DEFAULT NULL

extern const pb_msgdesc_t SBI_iot_common_FanspeedSet_msg;
extern const pb_msgdesc_t SBI_iot_common_FanspeedBoundary_msg;
extern const pb_msgdesc_t SBI_iot_common_TemperatureSetPoint_msg;
extern const pb_msgdesc_t SBI_iot_common_Date_msg;
extern const pb_msgdesc_t SBI_iot_common_Time_msg;
extern const pb_msgdesc_t SBI_iot_common_DateTime_msg;
extern const pb_msgdesc_t SBI_iot_common_Version_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SBI_iot_common_FanspeedSet_fields &SBI_iot_common_FanspeedSet_msg
#define SBI_iot_common_FanspeedBoundary_fields &SBI_iot_common_FanspeedBoundary_msg
#define SBI_iot_common_TemperatureSetPoint_fields &SBI_iot_common_TemperatureSetPoint_msg
#define SBI_iot_common_Date_fields &SBI_iot_common_Date_msg
#define SBI_iot_common_Time_fields &SBI_iot_common_Time_msg
#define SBI_iot_common_DateTime_fields &SBI_iot_common_DateTime_msg
#define SBI_iot_common_Version_fields &SBI_iot_common_Version_msg

/* Maximum encoded size of messages (where known) */
#define SBI_iot_common_DateTime_size             46
#define SBI_iot_common_Date_size                 18
#define SBI_iot_common_FanspeedBoundary_size     12
#define SBI_iot_common_FanspeedSet_size          8
#define SBI_iot_common_TemperatureSetPoint_size  7
#define SBI_iot_common_Time_size                 24
#define SBI_iot_common_Version_size              18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
