#ifndef _FWCONFIG_H_
#define _FWCONFIG_H_

#define FWCONFIG_DEVMODE (1)

// Tasks
#define FWCONFIG_IOTTASK_PRIORITY (tskIDLE_PRIORITY + 1)
#define FWCONFIG_IOTTASK_NAME "IoT_Task"
#define FWCONFIG_IOTTASK_STACKSIZE (1024 * 8)

#define FWCONFIG_OTACHECKTASK_PRIORITY (tskIDLE_PRIORITY + 1)
#define FWCONFIG_OTACHECK_TASK_NAME "OTA-Update"
#define FWCONFIG_OTACHECK_TASK_STACKSIZE (8000)
#define FWCONFIG_OTACHECK_HTTP_GET_TIMEOUT (15000)

#define FWCONFIG_HTTPTASK_PRIORITY (tskIDLE_PRIORITY + 2)
#define FWCONFIG_MAINTASK_PRIORITY (tskIDLE_PRIORITY + 5)


// Wi-Fi (Soft Access Point)
#define FWCONFIG_STAAP_WIFI_SSID "SBI-Iot-Svr-%02X%02X%02X"

// Maintenance access
#define FWCONFIG_MAINTENANCEACCESS_PASSWORD "UFEC23SBI"

// MDNS
#define FWCONFIG_MDNS_HOSTNAME "sbi-iot-svr"

// Options
#define FWCONFIG_SDCARD_ISACTIVE (1)
#define FWCONFIG_SDCARD_ROOTPATH "/sdcard"

// SPIFF
#define FWCONFIG_SPIFF_ROOTPATH "/spiffs"
#define FWCONFIG_SPIFF_PARTITION "storage"

// OTA URL
#define FWCONFIG_OTA_URL "https://sbistoragecount.blob.core.windows.net/firmware/updateBoardNovikaVersion.json"

#endif