#ifndef _HARDWAREGPIO_H_
#define _HARDWAREGPIO_H_

#include <stdbool.h>

#include "driver/uart.h"
#include "driver/gpio.h"

// Mapping version 0.0
// #define HWGPIO_BRIDGEUART_TXD (17)
// #define HWGPIO_BRIDGEUART_RXD (16)
// #define HWGPIO_BRIDGEUART_RTS (UART_PIN_NO_CHANGE)
// #define HWGPIO_BRIDGEUART_CTS (UART_PIN_NO_CHANGE)
// 
// #define HWGPIO_SANITY_LED_PIN (0)
// 
// #define HWGPIO_BRIDGEUART_PORT_NUM      (UART_NUM_2)
// #define HWGPIO_BRIDGEUART_BAUDRATE      (115200)

// #define HWGPIO_BRIDGEUART_BUFFSIZE 255

// Mapping version 0.1
#define HWGPIO_SANITYLED_PIN (0)
#define HWGPIO_STATUSLED0_PIN (22)
#define HWGPIO_STATUSLED1_PIN (23)

#define HWGPIO_UART_DEV0_TX (1)
#define HWGPIO_UART_DEV0_RX (3)

#define HWGPIO_STM32_BOOT1_PIN (18)
#define HWGPIO_STM32_RESET_PIN (19)
#define HWGPIO_STM32_BOOT0_PIN (21)


// Communication between the STM32 and the ESP32
#define HWGPIO_BRIDGEUART_TXD_PIN (17)
#define HWGPIO_BRIDGEUART_RXD_PIN (16)
#define HWGPIO_BRIDGEUART_RTS_PIN (UART_PIN_NO_CHANGE)
#define HWGPIO_BRIDGEUART_CTS_PIN (UART_PIN_NO_CHANGE)
#define HWGPIO_BRIDGEUART_PORT_NUM (UART_NUM_2)
#define HWGPIO_BRIDGEUART_BAUDRATE (115200)
#define HWGPIO_BRIDGEUART_BUFFSIZE 255

#define HWGPIO_SDCARD_CS_PIN (15)
#define HWGPIO_SDCARD_MOSI_PIN (13)
#define HWGPIO_SDCARD_MISO_PIN (12)
#define HWGPIO_SDCARD_SCLK_PIN (14)

#define HWGPIO_BUZZER_ON_PIN (27)

#define HWGPIO_MODEL_BIT0_PIN (26)
#define HWGPIO_MODEL_BIT1_PIN (34)
#define HWGPIO_MODEL_BIT2_PIN (35)

void HARDWAREGPIO_Init();

void HARDWAREGPIO_SetSanity(bool bIsActive);

#endif