#ifndef _UFEC23PROTOCOL_H_
#define _UFEC23PROTOCOL_H_

#define UFEC23PROTOCOL_S2CFLAG (0x80)

typedef enum
{
    UFEC23PROTOCOL_FRAMEID_RESERVED0 = 0,

    UFEC23PROTOCOL_FRAMEID_C2SReqPingAlive = 1,
    UFEC23PROTOCOL_FRAMEID_S2CReqPingAliveResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqPingAlive,

    UFEC23PROTOCOL_FRAMEID_C2SReqVersion = 2,
    UFEC23PROTOCOL_FRAMEID_S2CReqVersionResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqVersion,

    UFEC23PROTOCOL_FRAMEID_C2SGetParameterJSON = 10,
    UFEC23PROTOCOL_FRAMEID_S2CGetParameterJSONResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SGetParameterJSON,

    UFEC23PROTOCOL_FRAMEID_C2SGetRunningSetting = 11,
    UFEC23PROTOCOL_FRAMEID_S2CGetRunningSettingResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SGetRunningSetting,

    UFEC23PROTOCOL_FRAMEID_C2SSetRunningSetting = 12,
    UFEC23PROTOCOL_FRAMEID_S2CSetRunningSettingResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SSetRunningSetting,

    // Parameter table related
    /*
    UFEC23PROTOCOL_FRAMEID_C2SReqParameterTableInfo = 9,
    UFEC23PROTOCOL_FRAMEID_S2CReqParameterTableInfoResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqParameterTableInfo,
    UFEC23PROTOCOL_FRAMEID_C2SReqParameterGet = 10,
    UFEC23PROTOCOL_FRAMEID_S2CReqParameterGetResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqParameterGet   */ 
} UFEC23PROTOCOL_FRAMEID;

#endif