#ifndef _UART_PROTOCOL_COMMON_H_
#define _UART_PROTOCOL_COMMON_H_

#define UARTPROTOCOLCOMMON_MAXPAYLOAD 1024

#define UARTPROTOCOLCOMMON_START_BYTE 0xCC
#define UARTPROTOCOLCOMMON_STOP_BYTE 0x99

#endif