#ifndef _UFEC23PROTOCOL_H_
#define _UFEC23PROTOCOL_H_

#define UFEC23PROTOCOL_RESPONSEFLAG (0x80)

typedef enum
{
    UFEC23PROTOCOL_FRAMEID_RESERVED0 = 0,

    UFEC23PROTOCOL_FRAMEID_C2SReqVersion = 1,
    UFEC23PROTOCOL_FRAMEID_S2CReqVersionResp = UFEC23PROTOCOL_RESPONSEFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqVersion,

    UFEC23PROTOCOL_FRAMEID_C2SReqParameterBegin = 10,
    UFEC23PROTOCOL_FRAMEID_S2CReqParameterBeginResp = UFEC23PROTOCOL_RESPONSEFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqParameterBegin,
    UFEC23PROTOCOL_FRAMEID_C2SReqParameterGet = 11,
    UFEC23PROTOCOL_FRAMEID_S2CReqParameterGetResp = UFEC23PROTOCOL_RESPONSEFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqParameterGet,
    
} UFEC23PROTOCOL_FRAMEID;

#endif