#ifndef _UFEC23PROTOCOL_H_
#define _UFEC23PROTOCOL_H_

#define UFEC23PROTOCOL_RESPONSEFLAG (0x80)

typedef enum
{
    UFEC23PROTOCOL_FRAMEID_RESERVED0 = 0,

    UFEC23PROTOCOL_FRAMEID_C2SReqPingAlive = 1,
    UFEC23PROTOCOL_FRAMEID_S2CReqPingAliveResp = UFEC23PROTOCOL_RESPONSEFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqPingAlive,

    UFEC23PROTOCOL_FRAMEID_C2SReqVersion = 2,
    UFEC23PROTOCOL_FRAMEID_S2CReqVersionResp = UFEC23PROTOCOL_RESPONSEFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqVersion,

    UFEC23PROTOCOL_FRAMEID_C2SGetParameterJSON = 10,
    UFEC23PROTOCOL_FRAMEID_S2CGetParameterJSON = UFEC23PROTOCOL_RESPONSEFLAG | UFEC23PROTOCOL_FRAMEID_C2SGetParameterJSON,

    // Parameter table related
    /*
    UFEC23PROTOCOL_FRAMEID_C2SReqParameterTableInfo = 9,
    UFEC23PROTOCOL_FRAMEID_S2CReqParameterTableInfoResp = UFEC23PROTOCOL_RESPONSEFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqParameterTableInfo,
    UFEC23PROTOCOL_FRAMEID_C2SReqParameterGet = 10,
    UFEC23PROTOCOL_FRAMEID_S2CReqParameterGetResp = UFEC23PROTOCOL_RESPONSEFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqParameterGet   */ 
} UFEC23PROTOCOL_FRAMEID;

#endif