#ifndef _UFEC23PROTOCOL_H_
#define _UFEC23PROTOCOL_H_

#define UFEC23PROTOCOL_S2CFLAG (0x80)

typedef enum
{
    UFEC23PROTOCOL_FRAMEID_RESERVED0 = 0,

    UFEC23PROTOCOL_FRAMEID_A2AReqPingAlive = 1,
    UFEC23PROTOCOL_FRAMEID_A2AReqPingAliveResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_A2AReqPingAlive,

    //UFEC23PROTOCOL_FRAMEID_C2SReqVersion = 2,
    //UFEC23PROTOCOL_FRAMEID_S2CReqVersionResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqVersion,

    UFEC23PROTOCOL_FRAMEID_C2SGetRunningSetting = 11,
    UFEC23PROTOCOL_FRAMEID_S2CGetRunningSettingResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SGetRunningSetting,

    //UFEC23PROTOCOL_FRAMEID_C2SSetRunningSetting = 12,
    //UFEC23PROTOCOL_FRAMEID_S2CSetRunningSettingResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SSetRunningSetting,

    UFEC23PROTOCOL_FRAMEID_C2SGetParameter = 15,
    UFEC23PROTOCOL_FRAMEID_S2CGetParameterResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SGetParameter,

    UFEC23PROTOCOL_FRAMEID_C2SSetParameter = 16,
    UFEC23PROTOCOL_FRAMEID_S2CSetParameterResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SSetParameter,

    UFEC23PROTOCOL_FRAMEID_C2SSendDebugData = 17,
    UFEC23PROTOCOL_FRAMEID_S2CSendDebugDataResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SSendDebugData,

	UFEC23PROTOCOL_FRAMEID_S2CEvent = UFEC23PROTOCOL_S2CFLAG | 100,
    //UFEC23PROTOCOL_FRAMEID_C2SCommitParameter = 17,
    // UFEC23PROTOCOL_FRAMEID_S2CCommitParameter = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SCommitParameter,

    // Parameter table related
    /*
    UFEC23PROTOCOL_FRAMEID_C2SReqParameterTableInfo = 9,
    UFEC23PROTOCOL_FRAMEID_S2CReqParameterTableInfoResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqParameterTableInfo,
    UFEC23PROTOCOL_FRAMEID_C2SReqParameterGet = 10,
    UFEC23PROTOCOL_FRAMEID_S2CReqParameterGetResp = UFEC23PROTOCOL_S2CFLAG | UFEC23PROTOCOL_FRAMEID_C2SReqParameterGet   */ 
} UFEC23PROTOCOL_FRAMEID;

#endif
